#! /bin/sh
case "$1" in
    start)
        echo "S98Modules start"
        echo "Load scull"
        /bin/scull_load
        echo "Load faulty"
        /bin/module_load faulty
        echo "Load aesdchar"
        /bin/module_load aesdchar
        echo "modprobe hello"
        modprobe hello
        ;;
    stop)
        echo "S98Modules stop unload scull, faulty"
        /bin/scull_unload
        /bin/module_unload faulty
        /bin/module_unload aesdchar
        rmmod hello  
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0